### ISSUE TITLE
submodules have moved

### ISSUE THREAD

**Issue by ast** [hraban/opus#1]
Submodules have moved so it doesn't build "out of the box" anymore.

    https://github.com/xiph/opus
    https://github.com/xiph/opusfile.git

**Comment by bwmarrin** [comment]
ahh I was having trouble with this too :)  Is there a work around to get it to go?

**Comment by hraban** [comment]
Hey guys I'm sorry about this, somehow I completely missed it. Do you happen to know an easy way to fix this?

**Comment by hraban** [comment]
Hm, actually, it seems git.xiph.org is back online. Just checked the whole thing out and it seems to work. Please feel free to reopen if it's back down.
