### ISSUE TITLE
Opus 1.3 release,would we update to new version?

### ISSUE THREAD

**Issue by cers000** [hraban/opus#21]
This Opus 1.3 major release
[https://people.xiph.org/~jm/opus/opus-1.3/](https://people.xiph.org/~jm/opus/opus-1.3/)

**Comment by hraban** [comment]
Updating opus on your own machine should do the trick, no update required from this package. I haven't tested the api, but their versioning suggests it's backwards compatible, so it should all work without requiring to update this wrapper.

Remember that this is just a wrapper around a c library, not the actual library itself. It is dynamically linked and configured using pkgconfig, so it's your system that controls the actual libopus. All this does is translate APIs.

Try and update your system and let me know if there's any problems!
