### ISSUE TITLE
Inconsistent types in README

### ISSUE THREAD

**Issue by xiekeyi98** [hraban/opus#36]
https://github.com/hraban/opus/blame/v2/README.md#L94-L95

https://github.com/hraban/opus/blame/v2/README.md#L134-L136

dec.Decode accept `[]int16` but in demo we give it `[]byte` 
![image](https://user-images.githubusercontent.com/7782671/96975339-e8a8b380-154c-11eb-95b9-fa1d561c70eb.png)

**Comment by hraban** [comment]
🤦‍♂️

thanks!
