### ISSUE TITLE
Decode: corrupted stream

### ISSUE THREAD

**Issue by tisov** [hraban/opus#5]
Hello.
I have a file: 
Container: Ogg
Codec: Opus
Chanells: Mono
Sample Rate: 48000
[heyTel.ogg.zip](https://github.com/hraban/opus/files/553479/heyTel.ogg.zip)

And this code:

``` go
func TestDecode(t *testing.T) {
    data, err := ioutil.ReadFile("heyTel.ogg")
    if err != nil {
        t.Fatal(err)
    }

    const sampleRate = 48000
    const frameSizeMS = 60
    const frameSize = sampleRate * frameSizeMS / 1000

    pcm := make([]int16, int(frameSize))

    dec, err := opus.NewDecoder(sampleRate, 1)
    if err != nil || dec == nil {
        t.Fatal(fmt.Errorf("Error creating new decoder: %v", err))
    }
    n, err := dec.Decode(data, pcm)
    if err != nil {
        t.Fatal(fmt.Errorf("Couldn't decode data: %v", err))
    }
    if len(pcm) != n {
        t.Fatal(fmt.Errorf("Length mismatch: %d samples in, %d out", len(pcm), n))
    }
}
```

But i get

> Couldn't decode data: opus: corrupted stream

Could you tell me what's wrong? Thanks

**Comment by hraban** [comment]
Hi tisov, for ogg wrapped audio streams you have to use the opus.Stream type. See the api docs at https://Godoc.org/github.com/hraban/opus#Stream and see stream_test.go for an example.

Let me know how it works out for you!

**Comment by hraban** [comment]
Hi tisov, for ogg wrapped audio streams you have to use the opus.Stream
type. See the api docs at https://Godoc.org/github.com/hraban/opus#Stream
(I think? Is it down now or is it just my mobile connection being
crap?) and see stream_test.go for an example.

Let me know how it works out for you !

Cheers

**Comment by hraban** [comment]
Hi tisov, any update on this? I'd like to close the ticket :)

**Comment by tisov** [comment]
Hi, It's working now. Thank you =)
