### ISSUE TITLE
Issues with Audio Transmission in Golang WebRTC Application Using PortAudio and OPUS Encoding

### ISSUE THREAD

**Issue by Josepavese** [hraban/opus#55]
**Description**
Hello,
I am facing issues with a Go-based WebRTC application utilizing the GO/PION library. The application is designed to capture a video stream and make it available over a WebRTC connection, while also receiving audio via WebRTC and playing it through the system speakers. I am currently implementing the final module, which involves sending audio to the WebRTC connection. The system should capture the microphone stream using github.com/gordonklaus/portaudio, encode it in OPUS using gopkg.in/hraban/opus.v2, and write it to the output track added to the WebRTC connection.

**Problem**
The audio is not being heard on the other end of the WebRTC connection, despite the audio track being received correctly. On the receiving end (using JavaScript and HTML), there is mostly silence with occasional brief noises occurring at regular intervals. These noises do not appear when the connection is not established, indicating that data is being sent but may be improperly encoded or not following an appropriate bitrate.

**Environment**

- Golang version: 1.19
- PION version: v4.0.0
- PortAudio version: Latest
- OPUS version: v2
- Operating System: Ubuntu 20.04

**Code Excerpt**
` 	import(
		"github.com/gordonklaus/portaudio"
		"github.com/hajimehoshi/oto"
		"github.com/pion/webrtc/v4"
		"github.com/pion/webrtc/v4/pkg/media"
		"gopkg.in/hraban/opus.v2"
		"github.com/pion/rtp"
		"log"
		"runtime"
		"time"
	)`

	func main() {
		runtime.GOMAXPROCS(runtime.NumCPU()) // Utilize all available CPU cores

		outboundAudioTrack, err := webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{
			MimeType: webrtc.MimeTypeOpus,
		}, "audio", "pion")
		if err != nil {
			log.Fatalf("Failed to create audio track: %s", err)
		}

		// Initialize PortAudio
		if err := portaudio.Initialize(); err != nil {
			log.Fatalf("Failed to initialize PortAudio: %s", err)
		}
		defer portaudio.Terminate()

		go StartMicrophoneStream(outboundAudioTrack)
	}

	func StartMicrophoneStream(outboundAudioTrack *webrtc.TrackLocalStaticRTP) {
		// Open default microphone device
		stream, err := portaudio.OpenDefaultStream(1, 0, sampleRate, frameSize, readAudio)
		if err != nil {
			log.Fatalf("Failed to open default stream: %s", err)
		}
		defer stream.Close()

		// Start the audio stream
		if err := stream.Start(); err != nil {
			log.Fatalf("Failed to start stream: %s", err)
		}
		defer stream.Stop()

		log.Println("Microphone streaming started")

		// Keep the stream open
		select {}
	}

	func readAudio(in []int16) {
		// Log input buffer
		// log.Printf("Captured audio data: %v", inputBuffer)

		// Create Opus encoder
		encoder, err := opus.NewEncoder(sampleRate, channels, opus.AppVoIP)
		if err != nil {
			log.Fatalf("Failed to create Opus encoder: %s", err)
		}

		// Encode PCM to Opus
		packet := make([]byte, 4000) // Adjust size as needed
		n, err := encoder.Encode(in, packet)
		if err != nil {
			log.Printf("Error encoding PCM to Opus: %s", err)
			return
		}

		// Log encoded packet size
		// log.Printf("Encoded audio packet size: %d", n)

		// Create RTP packet
		rtpPacket := &rtp.Packet{
			Header: rtp.Header{
				Version:        2,
				PayloadType:    111,                           // Dynamic payload type for Opus
				SequenceNumber: uint16(time.Now().UnixNano()), // Use a more appropriate sequence number generator
				Timestamp:      uint32(time.Now().UnixNano() / int64(time.Millisecond)),
				SSRC:           12345,
			},
			Payload: packet[:n],
		}

		// Marshal RTP packet to bytes
		rawPacket, err := rtpPacket.Marshal()
		if err != nil {
			log.Printf("Error marshaling RTP packet: %s", err)
			return
		}

		// Log RTP packet details
		// log.Printf("RTP packet details: %v", rtpPacket.Header)

		// Send RTP packet over WebRTC track
		if err := outboundAudioTrack.WriteRTP(rtpPacket); err != nil {
			log.Printf("Error writing RTP packet to track: %s", err)
		} else {
			log.Printf("RTP packet sent: %d bytes", len(rawPacket))
		}
	}`

**Comment by hraban** [comment]
It looks like you're recreating the decoder instance on every incoming sample. See https://github.com/hraban/opus/issues/49

**Comment by Josepavese** [comment]
Thank you for your suggestion. I have moved the instantiation of the Opus encoder outside of the `readAudio` function and now it is instantiated once in the `main` function. Despite this change, the situation has not improved; the sound still does not arrive at the other end of the WebRTC connection. Here is the updated code:

```go
import (
	"github.com/gordonklaus/portaudio"
	"github.com/hajimehoshi/oto"
	"github.com/pion/webrtc/v4"
	"github.com/pion/webrtc/v4/pkg/media"
	"gopkg.in/hraban/opus.v2"
	"github.com/pion/rtp"
	"log"
	"runtime"
	"time"
)

const (
	sampleRate = 48000
	frameSize  = 960
	channels   = 1
)

var (
	encoder *opus.Encoder
	outboundAudioTrack *webrtc.TrackLocalStaticRTP
)

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU()) // Utilize all available CPU cores

	var err error
	outboundAudioTrack, err = webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{
		MimeType: webrtc.MimeTypeOpus,
	}, "audio", "pion")
	if err != nil {
		log.Fatalf("Failed to create audio track: %s", err)
	}

	// Initialize Opus encoder
	encoder, err = opus.NewEncoder(sampleRate, channels, opus.AppVoIP)
	if err != nil {
		log.Fatalf("Failed to create Opus encoder: %s", err)
	}

	// Initialize PortAudio
	if err := portaudio.Initialize(); err != nil {
		log.Fatalf("Failed to initialize PortAudio: %s", err)
	}
	defer portaudio.Terminate()

	go StartMicrophoneStream()
}

func StartMicrophoneStream() {
	// Open default microphone device
	stream, err := portaudio.OpenDefaultStream(1, 0, sampleRate, frameSize, readAudio)
	if err != nil {
		log.Fatalf("Failed to open default stream: %s", err)
	}
	defer stream.Close()

	// Start the audio stream
	if err := stream.Start(); err != nil {
		log.Fatalf("Failed to start stream: %s", err)
	}
	defer stream.Stop()

	log.Println("Microphone streaming started")

	// Keep the stream open
	select {}
}

func readAudio(in []int16) {
	// Encode PCM to Opus
	packet := make([]byte, 4000) // Adjust size as needed
	n, err := encoder.Encode(in, packet)
	if err != nil {
		log.Printf("Error encoding PCM to Opus: %s", err)
		return
	}

	// Create RTP packet
	rtpPacket := &rtp.Packet{
		Header: rtp.Header{
			Version:        2,
			PayloadType:    111,                           // Dynamic payload type for Opus
			SequenceNumber: uint16(time.Now().UnixNano()), // Use a more appropriate sequence number generator
			Timestamp:      uint32(time.Now().UnixNano() / int64(time.Millisecond)),
			SSRC:           12345,
		},
		Payload: packet[:n],
	}

	// Marshal RTP packet to bytes
	rawPacket, err := rtpPacket.Marshal()
	if err != nil {
		log.Printf("Error marshaling RTP packet: %s", err)
		return
	}

	// Send RTP packet over WebRTC track
	if err := outboundAudioTrack.WriteRTP(rtpPacket); err != nil {
		log.Printf("Error writing RTP packet to track: %s", err)
	} else {
		log.Printf("RTP packet sent: %d bytes", len(rawPacket))
	}
}
```

Despite these changes, the sound still does not reach the other end of the WebRTC connection. Any further suggestions or insights would be greatly appreciated.

Thank you!

**Comment by hraban** [comment]
Sorry there are too many moving parts to this for me to help you. I advise you to have a look at the test suite: it is quite extensive and has some instructions on how to take the samples and plot them in Excel to verify the actual signal. Once you've pared down your code to a minimally functional test case, you will probably find the bug. Unfortunately I can't help you without spending about an hour of my own time on it , and I'd rather not do that :D so godspeed my friend and good luck!

**Comment by hraban** [comment]
Just to clarify: if you actually find a bug in libopus, or this wrapper of libopus, I'd love to hear more. As it stands there is too much irrelevant code in your sample for me to be convinced it's actually a bug in (lib)opus (rather than in the rest of the code), or what that would be. If you simplify it all down to a very simple bit of code that still has the bug please repost it here and I'll have a closer look.

**Comment by arkadijs** [comment]
1. The RTP timestamp is not set correctly.
2. Opus accepts pre-defined fixed length frames so make sure what PortAudio produced match codec expectation. (it is not by default)
3. Try 20ms frames for best compatibility.

**Comment by Josepavese** [comment]
Hi @arkadijs ,

Thank you so much for your assistance! I followed your suggestion to adjust the RTP timestamp and frame length settings, and it worked perfectly!

Here’s the updated code snippet I used:

```
package main

import (
	"log"
	"time"

	"github.com/gordonklaus/portaudio"
	"github.com/pion/rtp"
	"gopkg.in/hraban/opus.v2"
)

const (
	sampleRate = 48000
	frameSize  = 960 // 20ms frame size for Opus at 48kHz
)

var (
	opusEncoder        *opus.Encoder
	outboundAudioTrack WebRTCTrack // Assuming you have defined this
	sequenceNumber     uint16
	timestamp          uint32
)

func main() {
	// Initialize PortAudio
	if err := portaudio.Initialize(); err != nil {
		log.Fatalf("Failed to initialize PortAudio: %s", err)
	}
	defer portaudio.Terminate()

	// Initialize Opus encoder
	var err error
	opusEncoder, err = opus.NewEncoder(sampleRate, 1, opus.AppVoIP)
	if err != nil {
		log.Fatalf("Failed to create Opus encoder: %s", err)
	}

	StartMicrophoneStream()
}

func StartMicrophoneStream() {
	// Open default microphone device
	stream, err := portaudio.OpenDefaultStream(1, 0, sampleRate, frameSize, readAudio)
	if err != nil {
		log.Fatalf("Failed to open default stream: %s", err)
	}
	defer stream.Close()

	// Start the audio stream
	if err := stream.Start(); err != nil {
		log.Fatalf("Failed to start stream: %s", err)
	}
	defer stream.Stop()

	log.Println("Microphone streaming started")

	// Keep the stream open
	select {}
}

func readAudio(inputBuffer []int16) {
	// Encode PCM to Opus
	packet := make([]byte, 4000) // Adjust size as needed
	n, err := opusEncoder.Encode(inputBuffer, packet)
	if err != nil {
		log.Printf("Error encoding PCM to Opus: %s", err)
		return
	}

	// Create RTP packet
	rtpPacket := &rtp.Packet{
		Header: rtp.Header{
			Version:        2,
			PayloadType:    111,       // Dynamic payload type for Opus
			SequenceNumber: sequenceNumber,
			Timestamp:      timestamp,
			SSRC:           12345,
		},
		Payload: packet[:n],
	}

	// Increment sequence number and timestamp
	sequenceNumber++
	timestamp += uint32(frameSize)

	// Marshal RTP packet to bytes
	rawPacket, err := rtpPacket.Marshal()
	if err != nil {
		log.Printf("Error marshaling RTP packet: %s", err)
		return
	}
	if rawPacket == nil {
		log.Printf("Error marshaling RTP packet: rawPacket is nil")
		return
	}

	// Send RTP packet over WebRTC track
	if err := outboundAudioTrack.WriteRTP(rtpPacket); err != nil {
		log.Printf("Error writing RTP packet to track: %s", err)
	} else {
		//log.Printf("RTP packet sent: %d bytes", len(rawPacket))
	}
}

```
I believe this updated example could be helpful for others looking to integrate Opus with PION/WebRTC, especially since there are few examples available online. 

If you have any further tips or insights, I’d love to hear them. 
Once again, thank you for your help in resolving this issue.
